language: python
python:
  - "3.5"
install:
  - pip install coveralls
script:
<<<<<<< HEAD
  - coverage run -m unittest test_rpn
after_success:
  coveralls
=======
  - python -m unittest
>>>>>>> parent of 0c51079... edited config file
